### ISSUE TITLE
event.origin check in message event handler fails

### ISSUE THREAD

**Issue by mnaamani** [coinbase/coinbase-javascript-sdk#2]
Visiting the `coinbase.com/oauth/authorize` redirects to `www.coinbase.com/oauth/authorize` 

So the check `event.origin !== Coinbase.base_url` is always true when handling the posted message 
https://github.com/coinbase/coinbase-javascript-sdk/blob/ea4bfa8f9e22b78dde5bcb02414cb10b99caccd0/coinbase.js#L28

And the success method is never called.

Sent a PR to fix this: https://github.com/coinbase/coinbase-javascript-sdk/pull/1

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
