### ISSUE TITLE
Invalid send_limit_period in OAuth authorize parameters

### ISSUE THREAD

**Issue by mnaamani** [coinbase/coinbase-javascript-sdk#3]
With reference to [OAuth2 Permissions docs](https://developers.coinbase.com/docs/wallet/coinbase-connect/permissions) the valid options for send_limit_period are: `day`,`week` and `month`

https://github.com/coinbase/coinbase-javascript-sdk/pull/1 updates the example to use correct option

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
